package Rift.Radio.error;

public enum ErrorType {

    Duplicated_SONG,
    FILE_NOT_FOUND,
    SONG_NOT_FOUND,
    PLAYLIST_NOT_FOUND,
    SONG_ALREADY_IN_PLAYLIST,
    LIKED_SONG_ALREADY_EXISTS,
    SONG_NOT_IN_PLAYLIST,
    LIKED_SONG_NOT_FOUND,
    PLAYLIST_ALREADY_EXISTS, MP3_ALREADY_EXIST

}
